"""Mapas de motivos usados na confirmacao de agenda.

Extraidos automaticamente do operacional.py (o app desktop) para nao divergirem.
Se a lista de motivos mudar la, rode de novo o extrator e substitua este arquivo.
"""

# Motivo de encerramento -> a visita foi produtiva?
MOTIVO_PRODUTIVO = {
    'Troca de ONU': True,
    'Troca de conector interno': True,
    'Cliente ausente': False,
    'Troca de conector externo': True,
    'Drop refeito': True,
    'Concluída': True,
    'Área de risco': False,
    'Entrada não autorizada': False,
    'Problema de infraestrutura': False,
    'Não cumprimento de agenda': False,
    'Interna cliente': False,
    'Normalizado sem intervenção técnica': True,
    'Chuva': False,
    'Provisionamento ONU': True,
    'Problema CTO': False,
    'Falha massiva': False,
    'Solicitação de reagendamento': False,
    'Reconexão externa - CTO': True,
    'Limpeza de conector interno': True,
    'Desistiu do serviço': False,
    'Reposição ONU': True,
    'Tubulação obstruída': False,
    'Abertura indevida': False,
    'Endereço não localizado': False,
    'Reconexão interna': True,
    'Troca de fonte': True,
    'Endereço incorreto': False,
    'Troca de cabo telefônico': True,
    'Reconfiguração ONU': True,
    'Situação de risco': False,
}

# Motivo de encerramento -> de quem foi a causa (ofensor)
MAPEAMENTO_MOTIVOS = {
    'CLIENTE - AUSENTE': 'CLIENTE',
    'REDE - FALHA MASSIVA': 'TÉCNICA',
    'CLIENTE - CAIXA CHEIA': 'TÉCNICA',
    'REDE - PROBLEMA DE INFRAESTRUTURA': 'TÉCNICA',
    'CLIENTE - REAGENDOU': 'CLIENTE',
    'CLIENTE - ENDERECO NAO LOCALIZADO': 'COMERCIAL',
    'CLIENTE - ENTRADA / AREA NAO LIBERADA': 'TÉCNICA',
    'REDE - PREDIO SEM MDU': 'TÉCNICA',
    'REDE - PROBLEMA DE REDE': 'TÉCNICA',
    'CLIENTE - ABERTURA INDEVIDA': 'COMERCIAL',
    'CLIENTE - DESISTIU DO SERVICO': 'CLIENTE',
    'CLIENTE - TUBULAÇÃO OBSTRUÍDA': 'TÉCNICA',
    'CLIENTE - INTERNA CLIENTE': 'TÉCNICA',
    'CAMPO - NÃO CUMPRIMENTO DE AGENDA': 'TÉCNICA',
    'CLIENTE - AREA/SITUAÇÃO DE RISCO': 'TÉCNICA',
    'CLIENTE - ABERTURA INDEVIDA REPARO': 'CLIENTE',
    'CAMPO - CHUVA': 'TÉCNICA',
    'CLIENTE - SUSPEITA DE FRAUDE': 'CLIENTE',
    'CAMPO - FALTA MATERIAL': 'TÉCNICA',
    'CLIENTE - MUDOU DE ENDERECO': 'CLIENTE',
    'CLIENTE - AREA/SITUAÇÃO DE RISCO RETIRADA': 'TÉCNICA',
    'CLIENTE - ENDEREÇO INCORRETO': 'COMERCIAL',
    'CLIENTE - SOLICITAÇÃO DE REAGENDAMENTO': 'CLIENTE',
    'Cliente ausente': 'CLIENTE',
    'Área de risco': 'TÉCNICA',
    'Entrada não autorizada': 'COMERCIAL',
    'Problema de infraestrutura': 'TÉCNICA',
    'Não cumprimento de agenda': 'TÉCNICA',
    'Interna cliente': 'TÉCNICA',
    'Chuva': 'TÉCNICA',
    'Problema CTO': 'TÉCNICA',
    'Falha massiva': 'TÉCNICA',
    'Solicitação de reagendamento': 'CLIENTE',
    'Desistiu do serviço': 'COMERCIAL',
    'Tubulação obstruída': 'TÉCNICA',
    'Abertura indevida': 'COMERCIAL',
    'Endereço não localizado': 'COMERCIAL',
    'Endereço incorreto': 'COMERCIAL',
    'Situação de risco': 'TÉCNICA',
}
